development:
  adapter:      postgresql
  database:     <%= ENV['DEV_DB'] %>
  encoding:     <%= ENV['ENCODING'] %>
  min_messages: <%= ENV['MIN_MESSAGES'] %>
  pool:         <%= ENV['POOL'] %>
  timeout:      <%= ENV['TIMEOUT'] %>

test:
  adapter:      postgresql
  database:     <%= ENV['TST_DB'] %>
  encoding:     <%= ENV['ENCODING'] %>
  min_messages: <%= ENV['MIN_MESSAGES'] %>
  pool:         <%= ENV['POOL'] %>
  timeout:      <%= ENV['TIMEOUT'] %>

production:
  adapter:      postgresql
  database:     <%= ENV['PRD_DB'] %>
  encoding:     <%= ENV['ENCODING'] %>
  min_messages: <%= ENV['MIN_MESSAGES'] %>
  pool:         <%= ENV['POOL'] %>
  timeout:      <%= ENV['TIMEOUT'] %>
