development: &default
  adapter:  		<%= ENV['DB_ADAPTER'] %>
  encoding: 		<%= ENV['ENCODING'] %>
  min_messages: <%= ENV['MIN_MESSAGES'] %>
  pool: 				<%= ENV['POOL'] %>
  timeout: 			<%= ENV['TIMEOUT'] %>
  database: 		<%= ENV['DEV_DB'] %>

test:
  <<: *default
  database: 		<%= ENV['TST_DB'] %>